### ISSUE TITLE
Issue with installing

### ISSUE THREAD

**Issue by AlexTheGoat69** [vertyco/upgrade-chat#2]
**Describe the bug**
When installing upchatpy using a requirement file, the installation fails due and thrwos an error. 

**To Reproduce**
1. Add upchatpy to requirement.
2. Install requirement file
3. Try to use library

**Expected behavior**
No error 

**Screenshots**

**Desktop (please complete the following information):**
ubuntu 20.04.6 lts
using python 3.11

![gh](https://github.com/user-attachments/assets/8694e664-fc92-4fe8-afa4-44c57ff9b682)
![gh2](https://github.com/user-attachments/assets/8092a18a-7f5f-4e55-910e-4378b950dfc0)
![gh3](https://github.com/user-attachments/assets/52aa4b8e-d8c0-4f3a-b36c-460bfca50002)

**Comment by vertyco** [comment]
@Vondyy have you tried running `pip install -U aiohttp` before trying to install the library? It is a requirement in the setup.py file but seems like its not being installed properly. Based on the screenshots I can only make assumptions that you're trying to install the library outside of a virtual environment or that the aiohttp install is broken somehow.

**Comment by AlexTheGoat69** [comment]
So, I use aiohttp on my own for my personal project so I do already have it previously installed before trying to install this. I use pterodactyl(isolated Docker containers) to host my project and I use requirement files as you can't directly use the console for discord.

**Comment by vertyco** [comment]
Try adding a line in your dockerfile or whatever entry point you use to manually install aiohttp, I don't use pterodactyl and thus can't directly support it so you may be on your own a bit figuring that one out. Sorry I cant help more than that.

**Comment by vertyco** [comment]
@Vondyy any luck?

**Comment by AlexTheGoat69** [comment]
I tried your solution but it didn't work. I ended up using your repo and copying the things I needed and it works fine now. I'm just unable to install it directly.

**Comment by vertyco** [comment]
interesting, its always something weird with Pterodactyl, glad you got it working using the code directly though! Guess we can close this now, best of luck!
